name: Label Issues

on:
    issues:
        types: [opened, reopened, edited]

jobs:
    triage_issues:
        if: ${{ github.repository_owner == 'zachwatkins' }}
        permissions:
            issues: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: github/issue-labeler@v3.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/issue-labeler.yml
                  include-title: 1
                  enable-versioned-regex: 0
