name: Lint using Prettier

on:
    workflow_dispatch:
    pull_request:
        paths:
            - '**.js'
            - '**.mjs'
            - '**.ts'
            - '**.tsx'
            - '**.yaml'
            - '**.yml'
            - '**.scss'
            - 'src/**.css'
            - .eslintrc.cjs
            - 'package-lock.json'
            - 'package.json'
            - .github/workflows/lint_prettier.yml

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    lint-prettier:
        permissions:
            contents: read
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v4
            - uses: zachwatkins/.github/.github/actions/node-npm-setup@main

            - name: Run linter
              run: npm run lint
