name: Lint using Prettier

on:
    workflow_dispatch:
    pull_request:
        paths:
            - '**.js'
            - '**.mjs'
            - '**.ts'
            - '**.tsx'
            - '**.yaml'
            - '**.yml'
            - '**.scss'
            - 'src/**.css'
            - .eslintrc.cjs
            - 'package-lock.json'
            - 'package.json'
            - .github/workflows/lint_js.yml

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    lint-js:
        uses: 'zachwatkins/.github/.github/workflows/lint_js.yml@main'
