name: PHP CodeSniffer

on:
    pull_request:
        paths:
            - '**.php'
            - '**.js'
            - '**.css'
            - '**.html'
            - '.github/workflows/phpcs.yml'

jobs:
    phpcs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'

            - name: Install Composer dependencies
              run: composer install --no-progress --no-suggest

            - name: Get changed files
              id: changes
              run: echo "::set-output name=files::$(git diff --name-only HEAD $(git merge-base HEAD ${{ github.event.pull_request.base.sha }}))"

            - name: Run PHP CodeSniffer
              run: vendor/bin/phpcs --standard=phpcs.xml.dist --ignore=*/vendor/*,*/node_modules/* ${{ steps.changes.outputs.files }}
