name: PHP CodeSniffer

on:
    pull_request:
        paths:
            - '**.php'
            - '**.js'
            - '**.css'
            - '**.html'
            - '.github/workflows/phpcs.yml'

jobs:
    phpcs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: mbstring, zip

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --no-interaction --no-autoloader

            - name: List changed files
              run: |
                  git diff --name-only -r HEAD^1 HEAD > changed_files.txt
                  cat changed_files.txt

            - name: Create PHP CodeSniffer Summary
              id: phpcs
              run: |
                  vendor/bin/phpcs --report-file=phpcs_summary.txt --file-list=changed_files.txt --basepath=. --standard=phpcs.xml.dist --report-width=120 --report=summary -q -w
              continue-on-error: true

            - name: Create PHP CodeSniffer Body
                  vendor/bin/phpcs --report-file=phpcs_body.txt --file-list=changed_files.txt --standard=phpcs.xml.dist --report-width=120 --report=code -q -w -s
              if: ${{ steps.phpcs.outputs.exit_code != 0 }}
              continue-on-error: true

            - name: Create pull request review
              uses: actions/github@v4
              if: ${{ steps.phpcs.outputs.exit_code != 0 }}
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  pull_request_number: ${{ github.event.pull_request.number }}
                  event_type: pull_request_review
                  body: |
                      PHP CodeSniffer found the following issues. See the comments below for more details.
                      ```
                      $(cat phpcs_summary.txt)
                      ```
                  comments: $(cat phpcs_body.txt)
