name: PHP CodeSniffer

on:
    pull_request:
        paths:
            - '**.php'
            - '**.js'
            - '**.css'
            - '**.html'
            - '.github/workflows/phpcs.yml'

jobs:
    phpcs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Get changes
              run: git diff --name-only -r HEAD^1 HEAD

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: mbstring, zip

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --no-interaction --no-autoloader

            - name: Run PHP CodeSniffer
              run: echo ${{ steps.changed-files.outputs.changed_files }} | vendor/bin/phpcs --standard=phpcs.xml.dist --ignore=*/vendor/*,*/node_modules/* {} \;
