name: Pull request opened

on:
    pull_request_target:
        types:
            - opened

jobs:
    notify-when-maintainers-cannot-edit:
        uses: zachwatkins/.github/.github/workflows/pull-request-submitter-check.yml@main
