name: Pull Request Labeler

on:
    pull_request:
        types:
            - opened
            - synchronize

permissions:
    contents: read
    pull-requests: write

jobs:
    label:
        uses: zachwatkins/.github/.github/workflows/pull-request-labeler.yml@main
