name: Pull Request Labeler

on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    label:
        uses: zachwatkins/.github/.github/workflows/pull-request-labeler.yml@main
