name: Pull Request Labeler

on:
    pull_request:

jobs:
    triage:
        if: github.repository_owner == 'zachwatkins'
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/pull-request-labeler.yml
                  sync-labels: true
