name: WordPress PHPUnit Test with SQLite

# **What it does**: Runs phpunit for a WordPress plugin or theme.
# **Why we have it**: Standardize the testing environment for WordPress plugins and themes.
# **Who does it impact**: Contributors and maintainers.

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        paths:
            - '**.php'
            - .github/workflows/test_phpunit_sqlite.yml

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    test-wordpress:
        if: github.repository_owner == 'zachwatkins'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  # Update the specific version of PHP to match the version used on your server.
                  php-version: '8.1'

            - uses: zachwatkins/.github/.github/actions/php-composer-setup@main

            - run: composer test
              env:
                  WP_SQLITE_MODE: enabled
